mysql:
  primary:
    persistence:
      size: 48Gi
    resources:
      limits:
        memory: 8Gi
redis:
  auth:
    enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false